lanche = 'Hambúrguer', 'Suco', 'Pizza', 'Pudim'
print(lanche)
print(lanche[0])
print(lanche[1:3])
print(lanche[2:])
print(lanche[-1])
print(lanche[-2])
print(lanche[-3:])
print(lanche[0:2])
print(lanche[:2])
print(lanche[1:3])
print(lanche[1:])
print(lanche[:])
print(lanche[::2])
print(lanche[::-1])
print(lanche[::-2])
print(lanche[::-1][0])
print(lanche[::-1][1])
print(lanche[::-1][2])
print(lanche[::-1][3])
print('For')
for c in lanche:
    print('Eu vou comer', c)
print('For com range')
for c in range(0, len(lanche)):
    print('Eu vou comer', lanche[c])
for pos, comida in enumerate(lanche):
    print(f'Eu vou comer {comida} na posição {pos}')
print(sorted(lanche))
print(lanche.count('Pizza'))
print(lanche.index('Pizza'))
print(lanche.index('Pizza', 1))
print(lanche.index('Pizza', 0, 3))
