nome = input('Qual é seu nome? ')
print('Prazer em e conhecer {:>20}'.format(nome))
print('Prazer em e conhecer {:<20}'.format(nome))
print('Prazer em e conhecer {:^20}'.format(nome))
print('Prazer em e conhecer {:=^20}'.format(nome))
print('Prazer em e conhecer {:=^20}'.format(nome))
print('Prazer em e conhecer {:=>20}'.format(nome))

n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
print('A soma vale {}'.format(n1+n2))
print('A subtração vale {}'.format(n1-n2))
print('A multiplicação vale {}'.format(n1*n2))
print('A divisão vale {}'.format(n1/n2))
print('A divisão inteira vale {}'.format(n1//n2))
print('A potência vale {}'.format(n1**n2))
print('A raiz quadrada vale {}'.format(n1**(1/2)))
print('A raiz cúbica vale {}'.format(n1**(1/3)))
print('A raiz quadrada vale {:.2f}'.format(n1**(1/2)))
print('A raiz cúbica vale {:.2f}'.format(n1**(1/3)))
print('A raiz quadrada vale {:.3f}'.format(n1**(1/2)))
print('A raiz cúbica vale {:.3f}'.format(n1**(1/3)))
