a = input('Digite algo: ')
print("O tipo primitivo dessse valor é ", type(a))
print("Só tem espaço? ", a.isspace())
print("è um número? ", a.isnumeric())
print("è alfabético? ", a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Está em letra maiusculas? ', a.isupper())
print('Está em letra minusculas? ', a.islower())
print('Está capitalizada? ', a.istitle())