np= input('Digite um valor: ')
print(np.isnumeric())
print(np.isalpha())
print(np.isalnum())
print(np.isupper())
print(np.isascii())
print(np.istitle())

n = input('Digite algo: ')
print(n.isnumeric())
print(n.isalpha())
print(n.isalnum())
print(n.isupper())
print(n.isascii())
print(n.istitle())
print(n.isdecimal())
print(n.isdigit())
print(n.isidentifier())
print(n.islower())
print(n.isprintable())
print(n.isspace())

