a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está capitalizada?', a.istitle())
print('É um printável?', a.isprintable())
print('É um identificador?', a.isidentifier())
print('É um dígito?', a.isdigit())
print('É um decimal?', a.isdecimal())
print('É um espaço?', a.isspace())
print('É um número?', a.isnumeric())
print('É um número real?', a.isdecimal())
print('É um número real?', a.isnumeric())
print('É um número real?', a.isdigit())
print('É um número real?', a.isdecimal())
